Backends tidyup
OpenBluetoothToolbox/SimpleBLE pull request #365
Opened 2024-11-18 19:41 UTC by jcarrano

This is a refactoring only PR to prepare for the multiple-backend support. The idea is to have file deletions and renames here so that the other diff, which will already have many changes, is not so huge.

I was able to test the Linux, Plain and Android versions. I had some trouble getting Windows to cooperate and I don't own a Mac to test the MacOS code.

Some of the code that is added here will later be removed with the backend changes.

2024-11-21 06:09 UTC, kdewald requested changes
FYI, the MacOS build is broken, see CI run for details.

Loved the idea of the Builder template class! I do however have a small request: Can we use a more explicit naming or namespacing for the `build`, `build_vec` and `collect_values` functions to prevent them from being this generic?

Something similar to the `CollectValues` class, could we name it `ValueCollector` instead?

2024-11-21 06:10 UTC, kdewald commented
The `clang-format` and `cppcheck` tests are currently failing (mostly from ongoing Android work), but please have a quick look to validate that nothing new is being added.

2024-11-23 06:55 UTC, kdewald commented on simpleble/src/builders/BuildVec.h
> +namespace SimpleBLE::builder {
I'll be slightly pedantic here, can we use `Factory` as the namespace?

2024-11-23 06:55 UTC, kdewald commented on simpleble/src/builders/BuilderBase.h
> +namespace SimpleBLE::builder {
I'll be slightly pedantic here, can we use `Factory` as the namespace?

2024-11-23 06:57 UTC, kdewald commented on simpleble/src/backends/macos/PeripheralMac.mm
> +#include "ServiceBase.h"
Objective-C files should use `import`

2024-11-23 06:58 UTC, kdewald commented on simpleble/src/CommonUtils.h
> +namespace SimpleBLE::util {
I'll be slightly pedantic here, can we use `Util` as the namespace?

2024-11-23 06:58 UTC, kdewald commented on simpleble/src/CommonUtils.h
> +auto values(const MAP& map) {
I think `collect_values` is correct if within the `Util` namespace

2024-11-23 06:59 UTC, kdewald commented on simpleble/src/backends/macos/AdapterMac.mm
> +#include "CommonUtils.h"
Duplicate import

2024-11-23 07:06 UTC, kdewald commented on simpleble/src/builders/BuildVec.h
>  #include "BuilderBase.h"
I think it makes sense to roll this file into `BuilderBase.h`

2024-11-23 07:07 UTC, kdewald commented on simpleble/src/backends/macos/PeripheralBaseMacOS.mm
> +#import <simpleble/Descriptor.h>
One of the imports is incorrect.

2024-11-26 19:29 UTC, jcarrano commented
The cppcheck is failing because it crashes, but when I run it locally it succeeds. Clang-format is complaining about files I did not touch.

2024-11-26 22:45 UTC, kdewald commented
> The cppcheck is failing because it crashes, but when I run it locally it succeeds. Clang-format is complaining about files I did not touch.

Yeah, a lot of that comes from the changes we're doing in the Android side, so no need to worry about that for now.

2024-11-28 05:08 UTC, kdewald approved these changes

2024-11-28 05:09 UTC, merged